### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by neysimoes** [Frontititi/frontititi.github.io#1]
- Domínio
- Gerador de estático
- Criar mais matérias
- Área para banners (eventos e/ou parceiros)
- Páginas: Sobre, envie sua treta...
- Consumir repos do FrontendBR e criar o menu (Vagas, open-source, fórum...)

**Comment by Xhamps** [comment]
Transforma em um milestone, e em issues separadas.
Assim consegue organizar melhor o que cada um está fazendo.
